NASNE_IP = '192.168.0.103'

TWITTER_CONSUMER_KEY = 'xxxxxxxxxx'
TWITTER_CONSUMER_SECRET = 'xxxxxxxxxx'
TWITTER_ACCESS_TOKEN = 'xxxxxxxxxx'
TWITTER_ACCESS_SECRET = 'xxxxxxxxxx'

LCD_WIDTH = 16
I2C_ADDR = 0x3f
I2C_BUS = 1

GPIO_PIN = 13
